import Head from "next/head";
import SideNavbar from "@/components/SideNavbar";
import Layout from "@/pages/Layout";

export default function Home() {
  return (
    <div className="bg-blue-200">
      <Head>
        <title>SVEN</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
      <Layout />
    </div>
  );
}
